### PR TITLE
Add missing dependency

### PR DESCRIPTION
**Pull request by abarth**

### CODE REVIEW

**Comment by abarth** [comment]
TBR @jamesr

**Comment by jamesr** [comment]
What uses this dep?

**Comment by abarth** [comment]
```
ERROR at //sky/shell/testing/test_runner.h:12:11: Can't include this header from here.
#include "mojo/common/binding_set.h"
          ^------------------------
The target:
  //sky/shell:mac_scaffolding
is including a file from the target:
  //mojo/common:common

It's usually best to depend directly on the destination target.
In some cases, the destination target is considered a subcomponent
of an intermediate target. In this case, the intermediate target
should depend publicly on the destination to forward the ability
to include headers.

Dependency chain (there may also be others):
  //sky/shell:mac_scaffolding -->
  //sky/engine:engine -->
  //sky/engine/platform:platform --[private]-->
  //mojo/environment:chromium --[private]-->
  //mojo/common:common
```

**Comment by jamesr** [comment]
Ah, I didn't run gn check for the Mac based builds. My bad!

**Pull request merged**
