### PR TITLE
Reimplement 'stretch' for flexible items correctly.

### PR DESCRIPTION
**Pull request by Hixie**
Fixes #698 to actually work.
Also, adds some debugging aids around Flex.
And a test to check this fix.

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
The test failure (CC @abarth) seems unrelated (and I didn't hit it when developing?), so I'm merging this in.

**Comment by abarth** [comment]
I think it's an issue with the new harness being flaky.  :(

**Comment by eseidel** [comment]
Thank you!

**Pull request merged**
