### PR TITLE
Set and remove the callbacks on the RenderObject when we create and remove it.

### PR DESCRIPTION
**Pull request by Hixie**
...and not when we mount and dismount.

Turns out that when we dismount, it's too late -- we've already set renderObject to null.

We also mark the mixed viewport as dirty when it is removed from its parent.
Without this, we try to reuse the child nodes in subsequent syncs, which is a disaster.

This also moves the ownership of the actual list of children back into MixedViewport. It scares me that the MixedViewport owner controls the lifetime of the MixedViewport child list.

### CODE REVIEW

**Comment by abarth** [comment]
Can you write a test for this?

**Comment by abarth** [comment]
Please test remounting too.  :)

**Comment by Hixie** [comment]
I wrote a test, which I'll submit separately. It found some more bugs, which are now fixed here.

**Comment by abarth** [comment]
LGTM

**Pull request merged**
