### PR TITLE
Remove dart-pub-cache

### PR DESCRIPTION
**Pull request by abarth**
There's no reason for us to have our own dart-pub-cache in the source tree.  We
can just use the default one on the system.

### CODE REVIEW

**Comment by abarth** [comment]
@chinmaygarde

**Comment by jamesr** [comment]
This means if I do a gclient sync from two different sky checkouts at the same time I get a corrupt pub cache, correct?

**Comment by abarth** [comment]
Yes, just like if you run `pub get` in two different Dart projects at the same time.

**Comment by chinmaygarde** [comment]
lgtm

**Pull request merged**
