### PR TITLE
Avoid cancelling touches on views on gesture recognition on iOS

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
Why is it now OK to cancel?

**Comment by chinmaygarde** [comment]
cancelsTouchesInView is YES by default. I just realized that property existed.

**Comment by eseidelGoogle** [comment]
lgtm

**Comment by chinmaygarde** [comment]
Fixes #326 
Fixes #323

**Pull request merged**
