### PR TITLE
Don’t flash a message while fitness data is loading

### LINKED ISSUE #542: Fitness app flashes "no data yet" while data loads from disk
We should probably start off white until the data load succeeds or fails?

### PR DESCRIPTION
**Pull request by collinjackson**
Fixes #542

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by eseidelGoogle** [comment]
@HansMuller also brought us a progress indicator which we could use during this load as well if you want.

**Comment by collinjackson** [comment]
I tried flashing the progress indicator but it didn't look good rendering for a fraction of a second, I think it's better to just show the data

**Comment by Hixie** [comment]
Another option is to show the message or progress indicator after a few milliseconds' delay. (Try this on a flaky network.)

**Pull request merged**
