### PR TITLE
Bump version requirements of sky package

### PR DESCRIPTION
**Pull request by johnmccutchan**
Bump version requirements of sky package

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
Did you mean to incldue all those commits?  You may want to rebase and squash.

**Comment by johnmccutchan** [comment]
@eseidelGoogle Fixed. PTAL.

**Comment by johnmccutchan** [comment]
@abarth as Eric is out today.

**Comment by abarth** [comment]
lgtm

**Pull request closed without merging**
