### PR TITLE
working on generating docs as part of the build

### PR DESCRIPTION
**Pull request by devoncarew**
- working on generating docs as part of the build

I created this PR to see how happy travis is with the changes; not yet ready for review :)

### CODE REVIEW

**Comment by abarth** [comment]
@krisgiesing was asking about this today

**Comment by devoncarew** [comment]
OK, I think this is ready now. It generates docs during the build. It does not yet update to firebase; I'll follow up about that in an email. It does add ~30 seconds to the build, so we could consider pushing it to a 2nd bot if the main build gets too slow. @abarth 

For now I manually pushed to https://skydocs.firebaseapp.com/index.html.

**Comment by abarth** [comment]
LGTM  Please squash commits before landing.

**Comment by devoncarew** [comment]
squashed! FYI, I don't have commit rights to domokit/sky_engine

**Comment by abarth** [comment]
Landed and fixed.

**Pull request merged**
