### PR TITLE
Change generic value names to be more descriptive for assert tracing.

### PR DESCRIPTION
**Pull request by apwilson**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM!

**Comment by Hixie** [comment]
Can you elaborate on what this does? These were all called "value" on purpose, to make the code easier to copy-paste, and in future make it easier to move to just using a macro to declare such properties.

If we're going to move away from "value" to using the property name with "new" on the front, then we should do this to all the setters across the codebase (there are many more than just this one file).

**Comment by abarth** [comment]
It changes the assert you get from `assert(value >= 0.0 && value <= 1.0);` to `assert(newOpacity >= 0.0 && newOpacity <= 1.0);` with the idea that would be easier to debug for the end-developer.

**Comment by Hixie** [comment]
We should probably put those asserts into the various RenderObjectWrapper constructors, so that the stack trace is good too.

**Comment by abarth** [comment]
Done in #968

**Pull request merged**
