### PR TITLE
Examples as libraries

### PR DESCRIPTION
**Pull request by jimsimon**
Examples converted:
* address_book
* demo_launcher
* fitness
* hello_world
* mine_digger
* stocks

Examples NOT converted:
* game
* raw
* rendering
* widgets

### CODE REVIEW

**Comment by abarth** [comment]
This looks great.

One question: have you signed the Google Contributor License Agreements?  I've just setup the bot that checks for that, but I think you uploaded your pull request before it was active:

https://cla.developers.google.com/clas

**Comment by jimsimon** [comment]
Yep, I signed it yesterday but if you want I can re-create the PR.

**Comment by jimsimon** [comment]
Yep, I signed it yesterday but if you want I can re-create the PR.

**Comment by abarth** [comment]
Thanks!  Hopefully you'll send more pull requests and the bot will check those.  ;)

**Pull request merged**
