### PR TITLE
Add SetRequestedOrientation to Activity service

### LINKED ISSUE #743: Allow locking to potrait and/or landscape mode
This can be done dynamically on android via:

http://developer.android.com/intl/es/reference/android/app/Activity.html#setRequestedOrientation(int)

See http://stackoverflow.com/questions/2366706/how-to-lock-orientation-during-runtime/10488012#10488012 for more details

### PR DESCRIPTION
**Pull request by abarth**
Fixes #743

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
I'm unclear as to what the two UNSPECIFIED and NOSENSOR values do.  Would someone ever want to pass NOSENSOR to this api?

**Comment by eseidelGoogle** [comment]
lgtm

**Comment by abarth** [comment]
Would you like me to link to the android documentation?  NOSENSOR means ignore the sensor and use the factory default orientation for the screen.

**Comment by eseidelGoogle** [comment]
Yes, a doc link sounds useful.

**Comment by Hixie** [comment]
Where did the "Title" class go? I don't see it in the diff.

**Comment by Hixie** [comment]
Nevermind, I see title.dart was checkin in separately.

**Pull request merged**
